name: main

on:
  push:
    tags:
      - '*'

jobs:
  build:
    # strategy:
    #   matrix:
    #     os: [macos-latest, ubuntu-latest, windows-latest]

    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - run: yarn install
      # TODO: Not there yet...
      # - run: xvfb-run -a npm test
      #   if: runner.os == 'Linux'
      # - run: npm test
      #   if: runner.os != 'Linux'
      # - if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      - env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm run deploy
