name: Test

on:
  push:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - run: xvfb-run -a yarn test
        if: runner.os == 'Linux'

      - run: yarn test
        if: runner.os != 'Linux'

      - uses: codecov/codecov-action@v2
        if: success() && matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          verbose: true
